Check the correct log in CI for errors.
Fixes #919.

diff --git a/Jenkinsfile-ubuntu-2004 b/Jenkinsfile-ubuntu-2004
--- a/Jenkinsfile-ubuntu-2004
+++ b/Jenkinsfile-ubuntu-2004
@@ -61,7 +61,9 @@ pipeline {
                 cd $SOURCE_PATH/shakenfist
                 . /home/jenkins/sf-ci
                 ansible-playbook -i /home/jenkins/hosts \
-                    --extra-vars "identifier=$BUILD_TAG source_path=$SOURCE_PATH base_image=label:sfci-image base_image_user=ubuntu" \
+                    --extra-vars "identifier=$BUILD_TAG source_path=$SOURCE_PATH \
+                    base_image=label:sfci-image \
+                    base_image_user=ubuntu" \
                     deploy/ansible/ci.yml
            '''
       }
@@ -69,7 +71,8 @@ pipeline {
     stage('Run installer on primary') {
       steps {
         sh '''  . $WORKSPACE/$BUILD_TAG/ci-environment.sh
-                ssh -i /home/jenkins/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
+                ssh -i /home/jenkins/id_ci -o StrictHostKeyChecking=no \
+                    -o UserKnownHostsFile=/dev/null \
                     ubuntu@$primary sudo /root/sf-deploy.sh
            '''
       }
@@ -77,8 +80,10 @@ pipeline {
     stage('Run CI tests on primary') {
       steps {
         sh '''  . $WORKSPACE/$BUILD_TAG/ci-environment.sh
-                scp -rp -i /home/jenkins/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
-                    $source_path/shakenfist ubuntu@$primary:shakenfist
+                scp -rp -i /home/jenkins/id_ci -o StrictHostKeyChecking=no \
+                    -o UserKnownHostsFile=/dev/null \
+                    $source_path/shakenfist \
+                    ubuntu@$primary:shakenfist
                 ssh -i /home/jenkins/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
                     ubuntu@$primary "cd shakenfist/deploy; tox -epy3"
            '''
@@ -86,29 +91,37 @@ pipeline {
     }
     stage('Log check') {
       steps {
-        sh '''  # Ensure we don't have any tracebacks
-                if [ `grep -c "Traceback (most recent call last):" /var/log/syslog` -gt 0 ]
+        sh '''  # Copy across syslog
+                mkdir -p $WORKSPACE_TMP
+                . $WORKSPACE/$BUILD_TAG/ci-environment.sh
+                scp -rp -i /home/jenkins/id_ci -o StrictHostKeyChecking=no \
+                    -o UserKnownHostsFile=/dev/null \
+                    ubuntu@$primary:/var/log/syslog \
+                    $WORKSPACE_TMP/syslog
+
+                # Ensure we don't have any tracebacks
+                if [ `grep -c "Traceback (most recent call last):" $WORKSPACE_TMP/syslog` -gt 0 ]
                 then
                   echo "We have tracebacks in the logs!"
                   exit 1
                 fi
 
                 # Ensure we didn't log any errors
-                if [ `grep -c "ERROR" /var/log/syslog` -gt 0 ]
+                if [ `grep -c "ERROR" $WORKSPACE_TMP/syslog` -gt 0 ]
                 then
                   echo "Errors were logged!"
                   exit 1
                 fi
 
                 # Ensure nothing died
-                if [ `grep -c "died" /var/log/syslog` -gt 0 ]
+                if [ `grep -c "died" $WORKSPACE_TMP/syslog` -gt 0 ]
                 then
                   echo "A process died!"
                   exit 1
                 fi
 
                 # Ensure no leaked vxlans
-                if [ `grep -c "Extra vxlans present" /var/log/syslog` -gt 0 ]
+                if [ `grep -c "Extra vxlans present" $WORKSPACE_TMP/syslog` -gt 0 ]
                 then
                   echo "vxlans leaked!"
                   exit 1
@@ -136,15 +149,17 @@ pipeline {
 
               echo "=============================="
               ssh -i /home/jenkins/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
-                  ubuntu@$primary sudo cat /etc/sf/sfrc
+                  ubuntu@$primary sudo cat /etc/sf/sfrc || true
 
               echo "=============================="
               ssh -i /home/jenkins/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
-                  ubuntu@$primary sudo cat /etc/sf/shakenfist.json
+                  ubuntu@$primary sudo cat /etc/sf/shakenfist.json || true
 
               echo "=============================="
+              # We do not use the locally cached syslog from the log check here,
+              # because if the CI run failed earlier, the log check was skipped.
               ssh -i /home/jenkins/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
-                  ubuntu@$primary sudo cat /var/log/syslog
+                  ubuntu@$primary sudo cat /var/log/syslog || true
 
               echo "=============================="
 
