Remove outstanding leases for removed networkinterfaces.
This means you can rapidly reuse IP addresses if you desire.
Fixes #1686.

diff --git a/.github/workflows/functional-tests-debian-11-slim-primary.yml b/.github/workflows/functional-tests-debian-11-slim-primary.yml
--- a/.github/workflows/functional-tests-debian-11-slim-primary.yml
+++ b/.github/workflows/functional-tests-debian-11-slim-primary.yml
@@ -181,6 +181,13 @@ jobs:
             exit 1
           fi
 
+          # Ensure we didn't see invalid leases causing DHCP failures
+          if [ `grep -c "not using configured address" ${GITHUB_WORKSPACE}/syslog` -gt 0 ]
+          then
+            echo "DHCP is failing, probably due to invalid leases!"
+            exit 1
+          fi
+
       - name: Gather logs
         if: ${{ ! cancelled() }}
         run: |
