Add Debian 12 as a tested host OS.

diff --git a/.github/workflows/scheduled-tests-develop-debian-12-slim-primary.yml b/.github/workflows/scheduled-tests-develop-debian-12-slim-primary.yml
--- a/.github/workflows/scheduled-tests-develop-debian-12-slim-primary.yml
+++ b/.github/workflows/scheduled-tests-develop-debian-12-slim-primary.yml
@@ -1,4 +1,4 @@
-name: Retest v07-debian-11-slim-primary
+name: Retest develop-debian-12-slim-primary
 
 on:
   workflow_dispatch:
@@ -6,7 +6,7 @@ on:
     - cron: '00 13 * * *'        # utc
 
 jobs:
-  v07-debian-11-slim-primary:
+  develop-debian-12-slim-primary:
     runs-on: self-hosted
     concurrency:
       group: ${{ github.workflow }}-${{ github.ref }}
@@ -28,7 +28,7 @@ jobs:
         with:
           path: shakenfist
           fetch-depth: 0
-          ref: v0.7-releases
+          ref: develop
 
       - name: Determine if there is any dependency between the repositories
         run: |
@@ -39,22 +39,8 @@ jobs:
           cd ${GITHUB_WORKSPACE}/shakenfist
           ansible-playbook -i /home/debian/ansible-hosts \
               --extra-vars "identifier=${SHAKENFIST_NAMESPACE} source_path=${GITHUB_WORKSPACE} \
-              base_image=sf://label/ci-images/debian-11 base_image_user=debian" \
+              base_image=sf://label/ci-images/debian-12 base_image_user=debian" \
               deploy/ansible/ci-topology-slim-primary.yml
-
-      - name: Copy CI tools to primary
-        run: |
-          . ${GITHUB_WORKSPACE}/ci-environment.sh
-          cd ${GITHUB_WORKSPACE}/shakenfist
-          scp -i /srv/github/id_ci -o StrictHostKeyChecking=no \
-              -o UserKnownHostsFile=/dev/null -rp tools \
-              debian@$primary:.
-
-      - name: Log github actions buffering status
-        run: |
-          . ${GITHUB_WORKSPACE}/ci-environment.sh
-          cd ${GITHUB_WORKSPACE}/shakenfist
-          tools/run_remote ${primary} python3 tools/buffer.py
 
       - name: Run getsf installer on primary
         run: |
@@ -156,25 +142,75 @@ jobs:
         if: always()
         run: |
           . ${GITHUB_WORKSPACE}/ci-environment.sh
-          cd ${GITHUB_WORKSPACE}/shakenfist
-          tools/run_remote ${primary} sudo /home/${baseuser}/tools/ci_event_checks.sh
+          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
+                -o UserKnownHostsFile=/dev/null \
+                debian@$primary sudo chmod ugo+r /var/log/syslog
+          scp -rp -i /srv/github/id_ci -o StrictHostKeyChecking=no \
+              -o UserKnownHostsFile=/dev/null \
+              debian@$primary:/var/log/syslog \
+              ${GITHUB_WORKSPACE}/syslog
+
+          failures=0
+
+          echo
+          etcd_conns=`grep -c "Building new etcd connection" ${GITHUB_WORKSPACE}/syslog || true`
+          echo "This CI run created $etcd_conns etcd connections."
+          if [ $etcd_conns -gt 5000 ]; then
+            echo "FAILURE: Too many etcd clients!"
+            failures=1
+          fi
+
+          echo
+          sigterms=`grep -c "Sent SIGTERM to " ${GITHUB_WORKSPACE}/syslog || true`
+          echo "This CI run sent $sigterms SIGTERM signals while shutting down."
+          if [ $sigterms -gt 50 ]; then
+            echo "FAILURE: Too many SIGTERMs sent!"
+            failures=1
+          fi
+
+          FORBIDDEN=("Traceback (most recent call last):"
+                     "ERROR sf"
+                     "ERROR gunicorn"
+                     " died"
+                     "Extra vxlan present"
+                     "Fork support is only compatible with the epoll1 and poll polling strategies"
+                     "not using configured address"
+                     "Dumping thread traces"
+                     "because it is leased to"
+                     "not committing online upgrade"
+                     "Received a GOAWAY with error code ENHANCE_YOUR_CALM"
+                     "ConnectionFailedError"
+                     "invalid JWT in Authorization header"
+                     "Libvirt Error: XML error"
+                     "Cleaning up leaked IPAM"
+                     "Cleaning up leaked vxlan"
+                     "Waiting to acquire lock"
+                     'apparmor="DENIED"'
+                     "Ignoring malformed cache entry")
+          IFS=""
+          for forbid in ${FORBIDDEN[*]}
+          do
+            if [ `grep -c "$forbid" ${GITHUB_WORKSPACE}/syslog || true` -gt 0 ]
+            then
+              echo "FAILURE: Forbidden string found in logs: $forbid"
+              failures=1
+            fi
+          done
+
+          if [ $failures -gt 0 ]; then
+              echo "...failures detected."
+              exit 1
+          fi
 
       # On Ubuntu 22.04 the cleaner is rated a CPU hog because of etcd cleanup
       # cost. That's not really something we can control, so just ignore the CPU
       # usage of that process instead.
-      - name: Check SF process CPU usage
+      - name: Check process CPU usage
         if: always()
         run: |
           . ${GITHUB_WORKSPACE}/ci-environment.sh
           ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
               debian@$primary '. /etc/sf/sfrc; sf-client node cpuhogs --ignore sf_cleaner'
-
-      - name: Check for reasonable data rates
-        if: always()
-        run: |
-          . ${GITHUB_WORKSPACE}/ci-environment.sh
-          cd ${GITHUB_WORKSPACE}/shakenfist
-          tools/run_remote ${primary} sudo /home/${baseuser}/tools/ci_event_checks.sh
 
       - name: Fetch and tweak inventory
         if: always()
@@ -204,7 +240,7 @@ jobs:
               --extra-vars "base_image_user=debian ansible_ssh_common_args='-o StrictHostKeyChecking=no'" \
               ${GITHUB_WORKSPACE}/shakenfist/deploy/ansible/ci-gather-logs.yml
 
-      - uses: actions/upload-artifact@v4
+      - uses: actions/upload-artifact@v3
         if: always()
         with:
           name: bundle.zip
@@ -216,7 +252,7 @@ jobs:
         if: success()
         run: |
           if [ $(echo "slim-primary" | grep -c "localhost") -gt 1 ]; then
-            base=$(echo "sf://label/ci-images/debian-11" | cut -f 5 -d "/")
+            base=$(echo "sf://label/ci-images/debian-12" | cut -f 5 -d "/")
             sf-client instance snapshot primary \
               --label_name ci-images/$base-$GITHUB_BASE_REF \
               --delete-snapshot-after-label --flatten
@@ -227,8 +263,8 @@ jobs:
         id: create-issue
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          SF_CI_NAME: v07-debian-11-slim-primary
-          SF_BRANCH: v0.7-releases
+          SF_CI_NAME: develop-debian-12-slim-primary
+          SF_BRANCH: develop
           SF_ACTION_RUN: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
         with:
           filename: shakenfist/.github/workflows/scheduled-tests-failure.md
